export const LOAD_CART = "LOAD_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const INCREASE_PRODUCT_QUANTITY = "INCREASE_PRODUCT_QUANTITY";
export const DECREASE_PRODUCT_QUANTITY = "DECREASE_PRODUCT_QUANTITY";

export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_TOTAL = "UPDATE_TOTAL";
